-- TALENTFORGE SQLite Database
-- Ported from the original PostgreSQL schema (talentforge_database.sql).
--   * UUID            -> TEXT (random 32-char hex generated by default)
--   * ENUM types      -> TEXT + CHECK constraints
--   * TIMESTAMPTZ     -> TEXT (ISO-8601 UTC)
--   * NUMERIC         -> REAL
--   * plpgsql trigger -> SQLite trigger

PRAGMA foreign_keys = ON;

DROP VIEW IF EXISTS pending_verifications;
DROP VIEW IF EXISTS student_profiles;
DROP TABLE IF EXISTS analytics_snapshots;
DROP TABLE IF EXISTS collaboration_tags;
DROP TABLE IF EXISTS collaboration_roles;
DROP TABLE IF EXISTS collaboration_members;
DROP TABLE IF EXISTS collaboration_posts;
DROP TABLE IF EXISTS recruiter_shortlists;
DROP TABLE IF EXISTS job_required_skills;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS verification_evidence;
DROP TABLE IF EXISTS verification_requests;
DROP TABLE IF EXISTS project_highlights;
DROP TABLE IF EXISTS project_technologies;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS github_activity;
DROP TABLE IF EXISTS assessments;
DROP TABLE IF EXISTS certificates;
DROP TABLE IF EXISTS student_skills;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS users;

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    external_id TEXT UNIQUE,
    name TEXT NOT NULL,
    email TEXT UNIQUE COLLATE NOCASE,
    password_hash TEXT,
    role TEXT NOT NULL CHECK (role IN ('student','teacher','admin','recruiter')),
    avatar_url TEXT,
    college TEXT,
    department TEXT,
    batch_year INTEGER,
    location TEXT,
    bio TEXT,
    headline TEXT,
    github_username TEXT,
    target_role TEXT,
    overall_score REAL DEFAULT 0 CHECK (overall_score BETWEEN 0 AND 100),
    available_for_hire INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

-- =========================
-- SKILLS
-- =========================
CREATE TABLE skills (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL CHECK (category IN ('Frontend','Backend','AI/ML','DevOps','Database','Mobile')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE student_skills (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    confidence_score REAL DEFAULT 0 CHECK (confidence_score BETWEEN 0 AND 100),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('verified','pending','needs_revision')),
    projects_count INTEGER NOT NULL DEFAULT 0 CHECK (projects_count >= 0),
    github_contributions INTEGER NOT NULL DEFAULT 0 CHECK (github_contributions >= 0),
    assessments_completed INTEGER NOT NULL DEFAULT 0 CHECK (assessments_completed >= 0),
    certificates_count INTEGER NOT NULL DEFAULT 0 CHECK (certificates_count >= 0),
    faculty_verified INTEGER NOT NULL DEFAULT 0,
    verifier_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    verified_at TEXT,
    projects_weight REAL DEFAULT 35,
    github_weight REAL DEFAULT 25,
    assessment_weight REAL DEFAULT 20,
    faculty_weight REAL DEFAULT 20,
    UNIQUE(student_id, skill_id)
);

CREATE TABLE certificates (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    issuer TEXT,
    certificate_url TEXT,
    issued_date TEXT,
    verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('verified','pending','needs_revision')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE assessments (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id TEXT REFERENCES skills(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    score REAL CHECK (score BETWEEN 0 AND 100),
    completed_at TEXT,
    verified_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE github_activity (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    username TEXT,
    repository_count INTEGER DEFAULT 0,
    total_commits INTEGER DEFAULT 0,
    contributions INTEGER DEFAULT 0,
    last_synced_at TEXT
);

-- =========================
-- PROJECTS
-- =========================
CREATE TABLE projects (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    external_id TEXT UNIQUE,
    title TEXT NOT NULL,
    tagline TEXT,
    description TEXT,
    domain TEXT NOT NULL CHECK (domain IN ('Web Development','AI & Machine Learning','Cloud & Systems','Mobile','Cybersecurity')),
    github_url TEXT,
    demo_url TEXT,
    is_faculty_verified INTEGER NOT NULL DEFAULT 0,
    verified_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    verification_date TEXT,
    stars INTEGER DEFAULT 0 CHECK (stars >= 0),
    commits INTEGER DEFAULT 0 CHECK (commits >= 0),
    contributors INTEGER DEFAULT 0 CHECK (contributors >= 0),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE project_members (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT,
    is_featured INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (project_id, student_id)
);

CREATE TABLE project_technologies (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, skill_id)
);

CREATE TABLE project_highlights (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    highlight TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0
);

-- =========================
-- TEACHER VERIFICATION
-- =========================
CREATE TABLE verification_requests (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    external_id TEXT UNIQUE,
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    verification_type TEXT NOT NULL CHECK (verification_type IN ('project','skill_assessment','certificate')),
    submitted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','changes_requested','rejected')),
    reviewed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TEXT,
    notes TEXT
);

CREATE TABLE verification_evidence (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    request_id TEXT NOT NULL REFERENCES verification_requests(id) ON DELETE CASCADE,
    github_repo_url TEXT,
    project_report_url TEXT,
    demo_url TEXT,
    certificate_issuer TEXT,
    assessment_score REAL CHECK (assessment_score BETWEEN 0 AND 100)
);

-- =========================
-- RECRUITER / JOBS
-- =========================
CREATE TABLE jobs (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    recruiter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company TEXT,
    title TEXT NOT NULL,
    department TEXT,
    min_confidence REAL DEFAULT 0 CHECK (min_confidence BETWEEN 0 AND 100),
    preferred_projects INTEGER DEFAULT 0 CHECK (preferred_projects >= 0),
    require_faculty_verification INTEGER NOT NULL DEFAULT 0,
    location_type TEXT NOT NULL CHECK (location_type IN ('Remote','Hybrid','Onsite')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE job_required_skills (
    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, skill_id)
);

-- job_id is nullable (general shortlist), so uniqueness is enforced by an expression index below.
CREATE TABLE recruiter_shortlists (
    recruiter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    student_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id TEXT REFERENCES jobs(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
CREATE UNIQUE INDEX ux_shortlist ON recruiter_shortlists(recruiter_id, student_id, IFNULL(job_id, ''));

-- =========================
-- COLLABORATION
-- =========================
CREATE TABLE collaboration_posts (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    external_id TEXT UNIQUE,
    creator_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    domain TEXT,
    max_members INTEGER NOT NULL DEFAULT 2 CHECK (max_members > 0),
    posted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE collaboration_members (
    post_id TEXT NOT NULL REFERENCES collaboration_posts(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    PRIMARY KEY (post_id, user_id)
);

CREATE TABLE collaboration_roles (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    post_id TEXT NOT NULL REFERENCES collaboration_posts(id) ON DELETE CASCADE,
    role_name TEXT NOT NULL
);

CREATE TABLE collaboration_tags (
    post_id TEXT NOT NULL REFERENCES collaboration_posts(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (post_id, tag)
);

-- =========================
-- ANALYTICS
-- =========================
CREATE TABLE analytics_snapshots (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    total_students INTEGER DEFAULT 0,
    verified_projects INTEGER DEFAULT 0,
    hiring_companies INTEGER DEFAULT 0,
    match_accuracy REAL DEFAULT 0,
    pending_verifications INTEGER DEFAULT 0,
    active_teachers INTEGER DEFAULT 0,
    total_skills_verified INTEGER DEFAULT 0,
    weekly_growth_rate REAL DEFAULT 0,
    captured_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_target_role ON users(target_role);
CREATE INDEX idx_users_available ON users(available_for_hire);
CREATE INDEX idx_student_skills_skill ON student_skills(skill_id);
CREATE INDEX idx_student_skills_confidence ON student_skills(confidence_score);
CREATE INDEX idx_projects_domain ON projects(domain);
CREATE INDEX idx_projects_verified ON projects(is_faculty_verified);
CREATE INDEX idx_project_members_student ON project_members(student_id);
CREATE INDEX idx_verification_status ON verification_requests(status);
CREATE INDEX idx_verification_student ON verification_requests(student_id);
CREATE INDEX idx_jobs_recruiter ON jobs(recruiter_id);
CREATE INDEX idx_collaboration_creator ON collaboration_posts(creator_id);

-- =========================
-- UPDATED_AT TRIGGERS
-- =========================
CREATE TRIGGER trg_users_updated AFTER UPDATE ON users
FOR EACH ROW WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE users SET updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER trg_projects_updated AFTER UPDATE ON projects
FOR EACH ROW WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE projects SET updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE id = NEW.id;
END;

-- =========================
-- VIEWS
-- =========================
CREATE VIEW student_profiles AS
SELECT
    u.id,
    u.external_id,
    u.name,
    u.headline,
    u.bio,
    u.avatar_url AS avatar,
    u.college,
    u.department,
    u.batch_year,
    u.overall_score,
    u.location,
    u.github_username,
    u.target_role,
    u.available_for_hire,
    u.is_active,
    (SELECT COUNT(*) FROM project_members pm WHERE pm.student_id = u.id) AS project_count,
    (SELECT COUNT(*) FROM student_skills ss WHERE ss.student_id = u.id AND ss.status = 'verified') AS verified_count,
    COALESCE((SELECT ga.total_commits FROM github_activity ga WHERE ga.student_id = u.id), 0) AS total_github_commits,
    COALESCE((SELECT ga.repository_count FROM github_activity ga WHERE ga.student_id = u.id), 0) AS repository_count
FROM users u
WHERE u.role = 'student';

CREATE VIEW pending_verifications AS
SELECT
    vr.id,
    vr.external_id,
    vr.student_id,
    u.external_id AS student_external_id,
    u.name AS student_name,
    u.avatar_url AS student_avatar,
    u.department AS student_department,
    vr.project_id,
    vr.title,
    vr.verification_type,
    vr.submitted_at,
    vr.status,
    vr.notes,
    vr.reviewed_at,
    r.name AS reviewer_name,
    ve.github_repo_url,
    ve.project_report_url,
    ve.demo_url,
    ve.certificate_issuer,
    ve.assessment_score
FROM verification_requests vr
JOIN users u ON u.id = vr.student_id
LEFT JOIN users r ON r.id = vr.reviewed_by
LEFT JOIN verification_evidence ve ON ve.request_id = vr.id;
